### Es 1
Hai a disposizione un file `data.csv` contenente dati mensili di traffico aereo con due colonne:

- `date`: data in formato `YYYY-MM` (mese/anno)
- `passengers`: numero di passeggeri per quel mese


Costruisci un modello di **regressione polinomiale** che approssima l’andamento del numero di passeggeri nel tempo.

1. Carica il dataset.
2. Convertilo in un formato numerico utilizzando una colonna `mese_numerico` che conti i mesi a partire da gennaio 1949.
3. Applica una regressione polinomiale (grado a tua scelta).
4. Calcola l’RMSE tra i valori reali e quelli predetti.
5. Visualizza i dati reali e la curva stimata con Plotly.

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import plotly.graph_objects as go
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split

In [69]:
df=pd.read_csv("data.csv")

print(df.head())
print(df.isnull().sum())

df["date"]=pd.to_datetime(df["date"])

      date  passengers
0  1949-01       112.0
1  1949-02       118.0
2  1949-03       132.0
3  1949-04       129.0
4  1949-05       121.0
date          0
passengers    1
dtype: int64

In [70]:
df["mese_numerico"]=np.arange(len(df))
df=df.dropna(subset=["passengers", "mese_numerico"])
df

          date  passengers  mese_numerico
0   1949-01-01       112.0              0
1   1949-02-01       118.0              1
2   1949-03-01       132.0              2
3   1949-04-01       129.0              3
4   1949-05-01       121.0              4
..         ...         ...            ...
125 1960-07-01       622.0            125
126 1960-08-01       606.0            126
127 1960-09-01       508.0            127
128 1960-10-01       461.0            128
130 1960-12-01       432.0            130

[130 rows x 3 columns]

In [73]:
grado=3

X = df[["mese_numerico"]]
y = df["passengers"]
modello=make_pipeline(
    PolynomialFeatures(degree=grado),
    LinearRegression())

modello.fit(X, y)
df["predicted"]=modello.predict(X)
df

          date  passengers  mese_numerico   predicted
0   1949-01-01       112.0              0  116.622872
1   1949-02-01       118.0              1  117.753690
2   1949-03-01       132.0              2  118.935917
3   1949-04-01       129.0              3  120.168995
4   1949-05-01       121.0              4  121.452364
..         ...         ...            ...         ...
125 1960-07-01       622.0            125  478.786131
126 1960-08-01       606.0            126  482.011140
127 1960-09-01       508.0            127  485.217688
128 1960-10-01       461.0            128  488.405216
130 1960-12-01       432.0            130  494.720976

[130 rows x 4 columns]

In [75]:
rmse=root_mean_squared_error(df["passengers"],df["predicted"])
print("RMSE:", rmse)

RMSE: 45.10933571813696

In [76]:
fig = go.Figure()


fig.add_trace(go.Scatter(
    x=df["date"],
    y=df["passengers"],
    mode="lines+markers",
    name="Dati reali"
    ))

fig.add_trace(go.Scatter(
    x=df["date"],
    y=df["predicted"],
    mode="lines",
    name="Estimated"
    ))

fig.update_layout(
    title="regressione polinomiale",
    xaxis_title="Data",
    yaxis_title="numero di passeggeri"
    )